### ISSUE TITLE
Designating Simulation Manager in Cfg File

### ISSUE THREAD

**Issue by DrAuxin** [westpa/westpa#109]
If I try to designate the simulation manager from the cfg file (even if it is the default simulation manager)
#####
west:
  system:
    driver: system.System
    module_path: $WEST_SIM_ROOT
  drivers:
    sim_manager: sim_manager.WESimManager
    module_path: $WEST_ROOT/src/west
#####
I am able to initialize the simulation, but when I attempt to run it, it appears a future immediately throws an exception (this appears essentially immediately)
####
exception caught; shutting down
-- ERROR    [w_run] -- Traceback (most recent call last):
  File "/ihome/lchong/pat53/anaconda3/envs/westpa/westpa-2020.01/lib/cmds/w_run.py", line 49, in <module>
    sim_manager.run()
  File "/ihome/lchong/pat53/anaconda3/envs/westpa/westpa-2020.01/src/west/sim_manager.py", line 628, in run
    self.propagate()
  File "/ihome/lchong/pat53/anaconda3/envs/westpa/westpa-2020.01/src/west/sim_manager.py", line 472, in propagate
    incoming = future.get_result()
  File "/ihome/lchong/pat53/anaconda3/envs/westpa/westpa-2020.01/lib/wwmgr/work_managers/core.py", line 330, in get_result
    raise self._exception.with_traceback(self._traceback)
TypeError: __traceback__ must be a traceback or None
####
It works fine without the cfg designation. Perhaps an import error.

**Comment by DrAuxin** [comment]
I have also found that the simulation manager has class west.sim_manager.WESimManager when not using cfg. but just sim_manager.WESimManager with cfg directions
