### ISSUE TITLE
Monte Carlo CI bootstrapping estimator returning array of None

### ISSUE THREAD

**Issue by jdrusso** [westpa/westpa#113]
I'm not particularly familiar with this part of the code, so please let me know what would be helpful in putting together a minimal working example to demonstrate this bug if it ends up not being reproducible.

I have some data I've obtained from running a hundred iterations of a simple ODLD double-well system under OpenMM+WESTPA. Attempting to run `w_ipa -ao` produces the following error:

```
File "[my conda path]/anaconda3/envs/westpa-2020/westpa-2020.03/lib/west_tools/mclib/__init__.py", line 103, in mcbs_ci_correl
    pre_calculated = pre_calculated[numpy.isfinite(pre_calculated)]
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Printing the contents of `pre_calculated` directly reveals that it's entirely populated with `None` values, so `numpy.isfinite()` raises that exception.

Appreciate any thoughts on this, or any additional information I could provide that would be helpful. I haven't tested this with any other system. Manually inspecting a trace of some trajectories shows that the data itself appears to be valid.

**Comment by castephens** [comment]
Hello, I was actually able to produce this error with my own data, curious as to what's causing it. I'm actually running w_assign and then w_reweight with the init and then kinetics argument. w_assign seems to produce an assign.h5 file with the correct content which I use for the w_reweight run. the init option also seems to populate the reweight.h5 file correctly, but I get 2 tracebacks pasted below, the seconds being similar to the previous pose, when executing a request for a kinetics or average analysis.` pre_calculated` also appears to be a list of `None` values. I've attached the files to reproduce this error. This is run using westpa v2020.05, python 3.9.7, linux OS.

thanks in advance! -Christina
[reweighting_error_input.tar.gz](https://github.com/westpa/westpa/files/7222040/reweighting_error_input.tar.gz)



`w_assign -r west.cfg -W west.h5 --states_from_file state_labels`
`w_reweight -r west.cfg init --first-iter 1 --last-iter 240 --step-iter 1`
`w_reweight -r west.cfg kinetics --first-iter 1 --last-iter 240 --step-iter 1`

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/cstephens/miniconda3/envs/westpa-2020.05/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/cstephens/miniconda3/envs/westpa-2020.05/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cstephens/miniconda3/envs/westpa-2020.05/westpa-2020.05/lib/west_tools/westpa/progress.py", line 169, in _reporter_loop
    if self._last_operation != self._operation or time.time() - self._last_update >= self.interval:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Traceback (most recent call last):
  File "/home/cstephens/miniconda3/envs/westpa-2020.05/westpa-2020.05/lib/west_tools/w_reweight.py", line 708, in <module>
    WReweight().main()
  File "/home/cstephens/miniconda3/envs/westpa-2020.05/westpa-2020.05/lib/west_tools/westtools/core.py", line 160, in main
    self.go()
  File "/home/cstephens/miniconda3/envs/westpa-2020.05/westpa-2020.05/lib/west_tools/westtools/core.py", line 322, in go
    self._subcommand.go()
  File "/home/cstephens/miniconda3/envs/westpa-2020.05/westpa-2020.05/lib/west_tools/w_reweight.py", line 438, in go
    self.w_postanalysis_reweight()
  File "/home/cstephens/miniconda3/envs/westpa-2020.05/westpa-2020.05/lib/west_tools/w_reweight.py", line 398, in w_postanalysis_reweight
    avg_rates = self.run_calculation(eval_block=_2D_eval_block, name='Average Rates', dim=2, do_averages=True, **submit_kwargs)
  File "/home/cstephens/miniconda3/envs/westpa-2020.05/westpa-2020.05/lib/west_tools/westtools/kinetics_tool.py", line 261, in run_calculation
    future_result = future.get_result(discard=True)
  File "/home/cstephens/miniconda3/envs/westpa-2020.05/westpa-2020.05/lib/wwmgr/work_managers/core.py", line 329, in get_result
    raise self._exception.with_traceback(self._traceback)
  File "/home/cstephens/miniconda3/envs/westpa-2020.05/westpa-2020.05/lib/wwmgr/work_managers/serial.py", line 22, in submit
    result = fn(*(args if args is not None else ()), **(kwargs if kwargs is not None else {}))
  File "/home/cstephens/miniconda3/envs/westpa-2020.05/westpa-2020.05/lib/west_tools/w_reweight.py", line 44, in _2D_eval_block
    ci_res = mcbs_ci_correl(dataset,estimator=reweight_for_c,
  File "/home/cstephens/miniconda3/envs/westpa-2020.05/westpa-2020.05/lib/west_tools/mclib/__init__.py", line 102, in mcbs_ci_correl
    pre_calculated = pre_calculated[numpy.isfinite(pre_calculated)]
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by atbogetti** [comment]
@jdrusso did you every figure out what was causing this?  @castephens I'll try to reproduce this with version 2020.05 and dig a little deeper into the code to see what is going on.

**Comment by atbogetti** [comment]
@castephens I was able to reproduce the error when running w_reweight with the kinetics option with version 2020.05 just as you posted.  I tried running w_ipa/w_direct and some other analysis tools and didn't get any errors with those.  I also checked the h5 files and all the datasets look reasonable (in terms of fluxes and populations).  This might be something with w_reweight.  I'll see what I can find.

**Comment by jdrusso** [comment]
> @jdrusso did you every figure out what was causing this? 

I did not, sorry. No idea what this ended up being in my case.
