### ISSUE TITLE
HUB for error messages discussion

### ISSUE THREAD

**Issue by jeremyleung521** [westpa/westpa#163]
## This is part of an initiative to improve error messages so end users can better know how to debug their simulation. 
This post will act as a hub where you can introduce new error messages of which you would like to improve. It will also link to other issues on specific error messages for further discussion and present potential fixes. You may present additional situations where those errors might appear in those issues.

### Simulating Setup ("Compile Time")
- Pcoord shape error #164
- assert abs(1 - norm) < EPS*(len(segments)+n_active_bins) 

### Running a Simulation ("Run Time")
- Divide by zero/out of list error
- Propagation fail

### Simulation Analysis  
- KeyError/Hash Error

**Comment by jeremyleung521** [comment]
I've noticed there is an older issue thread #26 on improving error messages that was never merged. (https://github.com/westpa/westpa/tree/error_handling).

I haven't had the chance to go through everything but I think it's definitely worth implementing some of those changes (that I've read) into WESTPA 2.0, especially if they fix some of the issues listed here.

**Comment by jeremyleung521** [comment]
_Repost of #167_ 

Sample Error:
sim_manager.py", line 696, in check_propagation "propagation failed for {:d} segments".format(len(failed_segments)) westpa.sim_manager.PropagationError: propagation failed for 14 segments 

Relevant Code:
https://github.com/westpa/westpa/blob/main/src/west/sim_manager.py#L524

Potential Causes:
- Error on the propagator end or resources end so the propagation failed
- Something wrong with Sim manager?

Potential Fixes:

1.  ??

**Comment by jeremyleung521** [comment]
_repost of #165_ 
See that issue for some of Matt and John's discussion on it.

Sample Error:
`assert abs(1 - norm) < EPS*(len(segments)+n_active_bins) `

Relevant Code:
https://github.com/westpa/westpa/blob/main/src/west/sim_manager.py#L143

Potential Causes:
- Tolerance in norm is not the most rigorous (https://groups.google.com/g/westpa-users/c/hu8UL6Ig2e4/m/7Bp1Y-556U4J)
- Custom system.py is causing problems where walkers are being removed
- bstate and tstate are overlapped so any walker is immediately recycled, causing weights to double
- <s> "loss" of probability just from accumulated floating point error </s> https://github.com/westpa/westpa/issues/165#issuecomment-947066531

Potential Fixes:
1.  Last point is fixed with explicit re-normalization in w_init (#214)

**Comment by jeremyleung521** [comment]
_repost of #185_
## More informative error message when paths in west.cfg do not exist

### Sample Error:
```
System is being built only off of the system driver
Restart plugin initialized
Maximum wallclock time: 14 days, 0:00:00

Mon Aug  9 16:34:09 2021
Iteration 1 (250 requested)
Beginning iteration 1
4 segments remain in iteration 1 (4 total)
1 of 52 (1.923077%) active bins are populated
per-bin minimum non-zero probability:       1
per-bin maximum probability:                1
per-bin probability dynamic range (kT):     0
per-segment minimum non-zero probability:   0.25
per-segment maximum non-zero probability:   0.25
per-segment probability dynamic range (kT): 0
norm = 1, error in norm = 0 (0*epsilon)
exception caught; shutting down
-- ERROR    [w_run] -- Traceback (most recent call last):
  File "/home/groups/ZuckermanLab/russojd/westpa/westpa/src/westpa/cli/core/w_run.py", line 62, in run_simulation
    sim_manager.run()
  File "/home/groups/ZuckermanLab/russojd/westpa/westpa/src/westpa/core/sim_manager.py", line 695, in run
    self.propagate()
  File "/home/groups/ZuckermanLab/russojd/westpa/westpa/src/westpa/core/sim_manager.py", line 540, in propagate
    incoming = future.get_result()
  File "/home/groups/ZuckermanLab/russojd/westpa/westpa/src/westpa/work_managers/core.py", line 334, in get_result
    raise self._exception.with_traceback(self._traceback)
TypeError: __traceback__ must be a traceback or None
```

### Relevant code:

### Potential causes:

When the paths provided in `west.cfg` don't exist, it can cause all sorts of arcane error messages that completely depend on the propagator. 

The above is an example of using the executable propagator w/ AMBER, when `seg_logs` and `traj_segs` don't exist. `w_init` even runs fine, but when you `w_run` you get the above.

### Potential fixes:

Ideally, a more meaningful traceback should get passed back (not sure why it doesn't get passed back up here). 

A really nice check would be making sure anything that's supposed to be a path in `west.cfg` is in fact a valid, existing path.

`self.segment_ref_template`, `self.basis_state_ref_template`, and `self.initial_state_ref_template` should be validated as paths whenever they're set in `westpa.rc`. Not sure where this happens

Similarly,  when loading in `stdout`/`stderr`/`stderr`/`cwd` at https://github.com/westpa/westpa/blob/westpa-2.0-restruct/src/westpa/core/propagators/executable.py#L142 we should use `yamlcfg.YAMLConfig.get_path` instead of `get`, which I think will handle validating the paths.

**Comment by jeremyleung521** [comment]
_repost of #170_
## w_pdist ValueError: Value out of bin boundaries
by jdrusso 


### Sample Error:
```
Traceback (most recent call last):
  ....
  File "/Users/russojd/anaconda3/envs/westpa-2020/westpa-2020.03/lib/west_tools/w_pdist.py", line 53, in _remote_bin_iter
    histnd(dset[:,ipt,:], binbounds, weights, out=iter_hist, binbound_check = False, ignore_out_of_range=ignore_out_of_range)
  File "fasthist/_fasthist.pyx", line 39, in fasthist._fasthist.histnd
  File "fasthist/_fasthist.pyx", line 101, in fasthist._fasthist.histnd
  File "fasthist/_fasthist.pyx", line 226, in fasthist._fasthist._histnd
ValueError: value nan at index 194 out of bin boundaries in dimension 0
```

### Relevant code:
`w_pdist`

### Potential causes:
Walker blowing up

This simulation was run for 3841 iterations. I managed to bracket in the problematic iteration to iteration 2752 by tweaking `--first-iter and --last-iter`. Here, row 191 of `west.h5/iterations/iter_00002752` shows that after 4 steps, this particular walker blew up and started reporting an infinity and then `NaN`s. This walker continued to report NaNs in subsequent iterations.

### Potential fixes:
This error should more explicitly indicate that a walker has blown up.

However, this does raise some additional questions -- `w_fluxanl` ran with no complaints on this data, and WESTPA apparently encountered these `NaN`s and silently kept running. Seems like we should at least raise a warning in the output of every iteration if there's a blown-up walker.


### Additional Comments:
by jdrusso
> After corresponding a bit with atbogetti it seems like indeed, WESTPA checks for explicit failure (i.e. crashing outright) of the propagator, but not for sensible values of the progress coordinate.
> I propose a simple check in the post-iteration for NaN or inf values. I'd love to hear thoughts on whether this would make more sense as a warning (one of your walkers has failed, proceed with caution) or an error (your dynamics are blowing up, fix it and start over)

**Comment by shubham-programmerr** [comment]
Hi, I’m Shubham and I’m new to WESTPA.
I’m interested in improving this error message as a first contribution (preparing for GSoC).
Is this issue still open, and do you have any pointers on where in the code I should start looking?
