### ISSUE TITLE
MAB Recycling does not wait for istate futures.

### ISSUE THREAD

**Issue by jeremyleung521** [westpa/westpa#333]
### Prerequisites

* [x] Can you reproduce the problem in safe mode?
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

**Describe the bug.** A clear and concise description of what the bug is.  
This is what was described in the mailing list.  While istate generation is usually quick, this specific instance takes ~15 minutes leading to a ConsistencyError because WESTPA appeared to have moved on without waiting. 

> ---------- Forwarded message ---------
> From: hayden...@gmail.com <Unknown>
> Date: Thursday, 3 August 2023 at 13:05:08 UTC-4
> Subject: Re: [westpa-users] MAB Recycing error
> To: westpa-users <Unknown>
> 
> 
> Hello,
> 
> I have also run into this error multiple times during my WESTPA simulation, and have noticed something that may be helpful to the WESTPA developers in debugging this issue.
> I'm using WESTPA version 2022.04.
> 
> Description of my calculation:
> My system contains three proteins: an antigen and two antibodies fabs. I initialized the three proteins approximately 20 angstroms apart from each other in random rotational/conformational states, basically following and extending the protocol of the barnase-barstar WE paper. I am attempting to use WESTPA to explore cooperative binding between the two antibodies by enhancing the sampling towards their native bound state (I have a pdb file with both antibodies bound). I am using two progress coordinates corresponding to the RMSD of anchor residues with respect to the native bound state, one pcoord for each antibody. I am using a recursive binning scheme, where I have defined four outer bins corresponding to the totally unbound initial state, two singly-bound intermediate states (one for each antibody fab), and a doubly-bound target state. Within the initial and intermediate states I am employing minimal adaptive binning. The simulation is run in steady state mode.
> 
> I have generated my system with 128 basis states which contain the three proteins in various configurational states., but do not contain any solvent.
> I have defined a gen_istate.sh script that takes the basis state, adds solvent (using GROMACS gmx solvate), adds ions (gmx genion), minimizes the solvent, relaxes the solvent with NVT for 50 ps, then relaxes the solvent with NPT for 50 ps. This istate generation process takes approximately 15 minutes per istate on the hardware I'm using. I'm running the simulation on four of NVIDIA's DGX A100 compute nodes (each node has 128 CPUs and 8 x A100 GPUs). I'm using the ZMQ work manager with mpirun to orchestrate communication between nodes.
> 
> The simulation began with WESTPA generating 1 initial state per basis state for a total of 128 initial states. At iteration 36 I tweaking the binning scheme slightly, adding more bins to the intermediate states and fewer to the unbound states, and WESTPA created another 109 initial states at iteration 37. I'm not sure why this occurred as no states has reached the target yet, but many trajectories were removed from bins within the unbound macrostate. I think these 109 initial states were added to my pool of available initial states, but not yet used.
> 
> For the next ~200 iterations, the calculation runs smoothly. However, once trajectories begin to be recycled, the 109 yet-unused initial states start to get used up. By iteration 300, the calculation fails with the consistency error previously described:
> exception caught; shutting down
> -- ERROR    [w_run] -- error message: need 10 initial states for recycling, but only 7 present
> -- ERROR    [w_run] -- Traceback (most recent call last):
>   File "/root/gmxenv/lib/python3.8/site-packages/westpa/cli/core/w_run.py", line 62, in run_simulation
>     sim_manager.run()
>   File "/root/gmxenv/lib/python3.8/site-packages/westpa/core/sim_manager.py", line 761, in run
>     self.run_we()
>   File "/root/gmxenv/lib/python3.8/site-packages/westpa/core/sim_manager.py", line 682, in run_we
>     self.we_driver.construct_next()
>   File "/root/gmxenv/lib/python3.8/site-packages/westpa/core/we_driver.py", line 875, in construct_next
>     self._run_we()
>   File "/root/gmxenv/lib/python3.8/site-packages/westpa/core/we_driver.py", line 651, in _run_we
>     self._recycle_walkers()
>   File "/root/gmxenv/lib/python3.8/site-packages/westpa/core/we_driver.py", line 386, in _recycle_walkers
>     raise ConsistencyError(
> westpa.core.we_driver.ConsistencyError: need 10 initial states for recycling, but only 7 present
> 
> 
> Following the direction above, I add in standard error and log files for istate generation in the west.cfg file. Then I restart my job an monitor it. What I notice is that the WESTPA simulation runs smoothly until new istates need to be generated, then calls the istates to be generated, then attempts to continue the computation before the istates are ready! How do I know? I observed my job crashing with the consistency error, I immediately checked my istate log files, and noticed that output was still actively being generated in the istate log file! GROMACS was still running, performing the requisite istate job as defined in gen_istate.sh (without error), but WESTPA was being impatient!
> 
> So I think the problem lies somewhere in the code that is responsible for orchestrating the generation of initial states. It appears to not correctly wait for gen_istate.sh to finish in my case.
> 
> Cheers,
> Hayden

**To Reproduce.** Steps to reproduce the behavior:  
N/A

**Expected behavior.** A clear and concise description of what you expected to happen.  
Next iteration prepared without error

**Actual behavior.** A clear and concise description of what actually happens.  

> westpa.core.we_driver.ConsistencyError: need 10 initial states for recycling, but only 7 present

**WESTPA version and platform.** Which version you're running, on what OS, and how it was built (e.g. conda, system libraries, manually installed dependencies)  
2022.04

**Additional context.** Add any other context about the problem here. If necessary config files are required to reproduce the bug, attach the files here here.

**Comment by jeremyleung521** [comment]
A quick look suggests that [MAB/Binless manager doesn't wait for the istate_futures](https://github.com/westpa/westpa/blob/westpa2/src/westpa/core/binning/mab_manager.py#L79) after it collectively assigns segments at the end of the an iteration.  Every other instance of istate generation (`get_istate_futures()`) are wrapped in a `while futures:` block, so will always wait until completion.

Is my read correct?

EDIT: #334 is a work-in-progress fix.

**Comment by jeremyleung521** [comment]
Fixed and Merged.
