### ISSUE TITLE
Cythonization Fails in Python <=3.9

### ISSUE THREAD

**Issue by jeremyleung521** [westpa/westpa#349]
### Prerequisites

* [x] Can you reproduce the problem in safe mode?
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

**Describe the bug.** A clear and concise description of what the bug is.  
This is related to #323. Something between 3 days ago and today broke cythonization of `_reweight.pyx` again. Essentially, during installation, it will source the scipy .pyd files with wrong paths, causing the cythonization process to fail. I previously was able to fix it by reversing import order.

Might or might not be related to Cython 3.0.3 released today, (Oct 5th, 2023).
Example of fail: https://github.com/westpa/westpa/actions/runs/6421219853

**To Reproduce.** Steps to reproduce the behavior:  
1. `python -m pip install westpa --no-binary westpa` in an environment without westpa, Needs to be Python 3.9 or lower.

**Expected behavior.** A clear and concise description of what you expected to happen.  
Successful installation.

**Actual behavior.** A clear and concise description of what actually happens.  
```
sys.version: 3.10.12 | packaged by conda-forge | (mai...
sys.prefix: /usr/share/miniconda3
sys.executable: /usr/share/miniconda3/bin/python
conda location: /usr/share/miniconda3/lib/python3.10/site-packages/conda
conda-build: None
conda-env: /usr/share/miniconda3/bin/conda-env
user site dirs: 

CIO_TEST: <not set>
CONDA: /usr/share/miniconda3
CONDA_DEFAULT_ENV: test_env
CONDA_EXE: /usr/share/miniconda3/bin/conda
CONDA_PKGS_DIR: /home/runner/conda_pkgs_dir
CONDA_PREFIX: /usr/share/miniconda3/envs/test_env
CONDA_PROMPT_MODIFIER: 
CONDA_PYTHON_EXE: /usr/share/miniconda3/bin/python
CONDA_ROOT: /usr/share/miniconda3
CONDA_SHLVL: 1
CURL_CA_BUNDLE: <not set>
DEPLOYMENT_BASEPATH: /opt/runner
GITHUB_EVENT_PATH: /home/runner/work/_temp/_github_workflow/event.json
GITHUB_PATH: /home/runner/work/_temp/_runner_file_commands/add_path_6c137587-d871-471c-8feb-6a7b1190fabd
LD_PRELOAD: <not set>
PATH: /usr/share/miniconda3/envs/test_env/bin:/usr/share/miniconda3/condabin:/usr/share/miniconda3/condabin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/runner/.dotnet/tools
REQUESTS_CA_BUNDLE: <not set>
SELENIUM_JAR_PATH: /usr/share/java/selenium-server.jar
SSL_CERT_FILE: <not set>
SWIFT_PATH: /usr/share/swift/usr/bin

Using pip 23.2.1 from /usr/share/miniconda3/envs/test_env/lib/python3.9/site-packages/pip (python 3.9)
Processing /home/runner/work/westpa/westpa
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=40.8.0
    Obtaining dependency information for setuptools>=40.8.0 from https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl.metadata
    Downloading setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
  Collecting wheel
    Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
    Downloading wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
  Collecting Cython>=0.29.16
    Obtaining dependency information for Cython>=0.29.16 from https://files.pythonhosted.org/packages/51/81/a1b6c0fdc987b37ab3fc7c683b396b55746e3067e71d8a9435e1d2f3b2d6/Cython-3.0.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
    Downloading Cython-3.0.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
  Collecting oldest-supported-numpy
    Obtaining dependency information for oldest-supported-numpy from https://files.pythonhosted.org/packages/94/9a/756fef9346e5ca2289cb70d73990b4c9f25446a885c1186cfb93a85e7da0/oldest_supported_numpy-2023.8.3-py3-none-any.whl.metadata
    Downloading oldest_supported_numpy-2023.8.3-py3-none-any.whl.metadata (9.5 kB)
  Collecting scipy>=0.19.1
    Obtaining dependency information for scipy>=0.19.1 from https://files.pythonhosted.org/packages/88/8c/9d1f74196c296046af1f20e6d3fc7fbb27387282315e1643f450bba14329/scipy-1.11.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
    Downloading scipy-1.11.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 5.0 MB/s eta 0:00:00
  Collecting versioneer-518
    Downloading versioneer_518-0.19-py2.py3-none-any.whl (17 kB)
  Collecting numpy==1.19.3 (from oldest-supported-numpy)
    Downloading numpy-1.19.3-cp39-cp39-manylinux2010_x86_64.whl (14.9 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB 114.4 MB/s eta 0:00:00
  INFO: pip is looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.
  Collecting scipy>=0.19.1
    Obtaining dependency information for scipy>=0.19.1 from https://files.pythonhosted.org/packages/a3/d3/f88285098505c8e5d141678a24bb9620d902c683f11edc1eb9532b02624e/scipy-1.11.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
    Downloading scipy-1.11.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (59 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 kB 21.9 MB/s eta 0:00:00
    Obtaining dependency information for scipy>=0.19.1 from https://files.pythonhosted.org/packages/08/25/035fe07fc32c5a8b314f882faa9d4817223fa5faf524d3fedcf17a4b9d22/scipy-1.11.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
    Downloading scipy-1.11.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (59 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 kB 21.1 MB/s eta 0:00:00
    Downloading scipy-1.10.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 76.2 MB/s eta 0:00:00
    Downloading scipy-1.10.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 75.5 MB/s eta 0:00:00
    Downloading scipy-1.9.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.8 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.8/33.8 MB 63.0 MB/s eta 0:00:00
  Downloading setuptools-68.2.2-py3-none-any.whl (807 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 108.7 MB/s eta 0:00:00
  Downloading wheel-0.41.2-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 24.9 MB/s eta 0:00:00
  Downloading Cython-3.0.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 127.0 MB/s eta 0:00:00
  Downloading oldest_supported_numpy-2023.8.3-py3-none-any.whl (4.8 kB)
  Installing collected packages: versioneer-518, wheel, setuptools, numpy, Cython, scipy, oldest-supported-numpy
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 1.19.3 which is incompatible.
  pandas 2.1.1 requires numpy>=1.22.4; python_version < "3.11", but you have numpy 1.19.3 which is incompatible.
  Successfully installed Cython-3.0.3 numpy-1.19.3 oldest-supported-numpy-2023.8.3 scipy-1.9.3 setuptools-68.2.2 versioneer-518-0.19 wheel-0.41.2
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  from .linalg cimport cython_blas, cython_lapack
  ^
  ------------------------------------------------------------

  /tmp/pip-build-env-6r5pq6h_/overlay/lib/python3.9/site-packages/scipy/linalg.pxd:1:0: 'scipy/linalg/linalg.pxd' not found

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  from .linalg cimport cython_blas, cython_lapack
  ^
  ------------------------------------------------------------

  /tmp/pip-build-env-6r5pq6h_/overlay/lib/python3.9/site-packages/scipy/linalg.pxd:1:0: 'scipy/linalg/linalg/cython_blas.pxd' not found

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  from .linalg cimport cython_blas, cython_lapack
  ^
  ------------------------------------------------------------

  /tmp/pip-build-env-6r5pq6h_/overlay/lib/python3.9/site-packages/scipy/linalg.pxd:1:0: 'scipy/linalg/linalg/cython_lapack.pxd' not found
  warning: src/westpa/core/reweight/_reweight.pyx:351:13: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
  warning: src/westpa/core/reweight/_reweight.pyx:351:21: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
  warning: src/westpa/core/reweight/_reweight.pyx:351:32: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
  warning: src/westpa/core/reweight/_reweight.pyx:352:15: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
  warning: src/westpa/core/reweight/_reweight.pyx:352:24: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
  warning: src/westpa/core/reweight/_reweight.pyx:352:35: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
  warning: src/westpa/core/reweight/_reweight.pyx:352:46: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
  warning: src/westpa/core/reweight/_reweight.pyx:352:54: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
  Compiling src/westpa/fasthist/_fasthist.pyx because it changed.
  Compiling src/westpa/trajtree/_trajtree.pyx because it changed.
  Compiling src/westpa/mclib/_mclib.pyx because it changed.
  Compiling src/westpa/core/binning/_assign.pyx because it changed.
  Compiling src/westpa/core/kinetics/_kinetics.pyx because it changed.
  Compiling src/westpa/core/reweight/_reweight.pyx because it changed.
  [1/6] Cythonizing src/westpa/core/binning/_assign.pyx
  [2/6] Cythonizing src/westpa/core/kinetics/_kinetics.pyx
  [3/6] Cythonizing src/westpa/core/reweight/_reweight.pyx
  Traceback (most recent call last):
    File "/usr/share/miniconda3/envs/test_env/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/share/miniconda3/envs/test_env/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/share/miniconda3/envs/test_env/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-6r5pq6h_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-6r5pq6h_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-6r5pq6h_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-6r5pq6h_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 155, in <module>
    File "<string>", line 59, in extensions
    File "/tmp/pip-build-env-6r5pq6h_/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
      cythonize_one(*args)
    File "/tmp/pip-build-env-6r5pq6h_/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
      raise CompileError(None, pyx_file)
  Cython.Compiler.Errors.CompileError: src/westpa/core/reweight/_reweight.pyx
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/share/miniconda3/envs/test_env/bin/python /usr/share/miniconda3/envs/test_env/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpz1c3yb39
  cwd: /home/runner/work/westpa/westpa
  Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**WESTPA version and platform.** Which version you're running, on what OS, and how it was built (e.g. conda, system libraries, manually installed dependencies)  

**Additional context.** Add any other context about the problem here. If necessary config files are required to reproduce the bug, attach the files here here.

**Comment by jeremyleung521** [comment]
This is fixed by #350, but leaving it up for a little bit to see if we want to unpin the cython version after upstream fixes.
